name: Hello World Maven Build

on:
  push:
    branches:
      - main

jobs:
 validate:
    runs-on: ubauntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2 
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: validate
      run: mvn validate

 compile:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2 
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: validate
       run: mvn validate
 
 test:  
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2 
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: validate
       run: mvn validate

 package: 
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2 
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: validate
       run: mvn validate

 build:   
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2 
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: Build with Maven
       run: mvn install

 install:  
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2 
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: Drploy to production
       run: mvn install

 deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2 
       with:
        distribution: 'adopt'
        java-version: '11'

     - name: Drploy to production
       run: mvn install

     
